#!/usr/bin/env bash
# Set up admin.streamsuite.io subdomain isolation.
#
# Prerequisite (you do this FIRST in AWS Route53):
#   A record: admin.streamsuite.io → 217.15.168.103
#   Wait ~2 min for DNS to propagate, verify with:
#     dig +short admin.streamsuite.io
#
# Then run on Hostinger as root:
#   sudo bash ~/streamsuite/admin-subdomain-setup.sh

set -euo pipefail

ADMIN_HOST=admin.streamsuite.io
HOSTINGER_IP=217.15.168.103
MAIN_CONF=/etc/nginx/sites-enabled/streamsuite

echo "─── 1/5 ─── Verify DNS resolves ───"
RESOLVED=$(dig +short A $ADMIN_HOST | tail -1)
if [[ -z "$RESOLVED" ]]; then
  echo "ERROR: $ADMIN_HOST does not resolve. Add Route53 A record first."
  exit 1
fi
if [[ "$RESOLVED" != "$HOSTINGER_IP" ]]; then
  echo "ERROR: $ADMIN_HOST resolves to $RESOLVED, expected $HOSTINGER_IP"
  exit 1
fi
echo "✓ $ADMIN_HOST → $RESOLVED"

echo
echo "─── 2/5 ─── Expand Let's Encrypt cert to include $ADMIN_HOST ───"
# Skip if cert already covers admin.streamsuite.io (idempotent re-runs).
if openssl x509 -in /etc/letsencrypt/live/streamsuite.io/fullchain.pem -noout -text 2>/dev/null | grep -q "DNS:$ADMIN_HOST"; then
  echo "✓ cert already includes $ADMIN_HOST — skipping renewal"
else
  EXISTING_EMAIL=$(grep -oP 'email = \K\S+' /etc/letsencrypt/cli.ini 2>/dev/null || echo aamore@streamsuite.io)
  # `certonly --nginx` issues/expands the cert via nginx HTTP-01 challenge
  # but does NOT try to modify any nginx server blocks (we write our own
  # restricted block below). www.streamsuite.io is excluded because that
  # DNS record was removed.
  certbot certonly --nginx --non-interactive --agree-tos --email "$EXISTING_EMAIL" \
    --expand --cert-name streamsuite.io \
    -d streamsuite.io -d $ADMIN_HOST
  echo "✓ cert now covers $ADMIN_HOST"
fi

echo
echo "─── 3/5 ─── Write admin-only server block ───"
# Certbot's auto-generated server block for $ADMIN_HOST will proxy_pass / to
# the Next.js app — which means admin.streamsuite.io would serve the customer
# dashboard too. We override that block to ONLY serve /admin/* + /api/admin/*
# and reject everything else with 404.
cat > /etc/nginx/sites-available/streamsuite-admin.override <<'EOF'
# Auto-generated by admin-subdomain-setup.sh — overrides certbot's default
# `location /` block on admin.streamsuite.io to restrict scope.

server {
    listen 443 ssl http2;
    server_name admin.streamsuite.io;

    ssl_certificate /etc/letsencrypt/live/streamsuite.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/streamsuite.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Block dotfiles
    location ~ /\. { deny all; return 404; }

    # ONLY admin paths.
    location /admin {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/admin {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # Health endpoint allowed (so UptimeRobot can monitor the subdomain too)
    location = /api/health {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
    }
    # Everything else: hard 404.
    location / {
        return 404;
    }
}

# HTTP redirect to HTTPS for the subdomain
server {
    listen 80;
    server_name admin.streamsuite.io;
    return 301 https://admin.streamsuite.io$request_uri;
}
EOF

# Symlink into sites-enabled. -f makes re-runs safe.
ln -sf /etc/nginx/sites-available/streamsuite-admin.override /etc/nginx/sites-enabled/streamsuite-admin.override

# Strip certbot's auto-added admin.streamsuite.io blocks from the main config
# so they don't conflict with our restricted block. Look for `server_name`
# lines containing admin.streamsuite.io and delete from `server {` to matching `}`.
python3 - <<PY
import re
path = "$MAIN_CONF"
with open(path) as f: src = f.read()
# Remove ALL server blocks whose server_name contains admin.streamsuite.io
def strip_admin_blocks(s):
    out = []
    depth = 0; buf = []; in_server = False; saw_admin = False
    i = 0
    blocks = []
    # naive parse: find each "server {" and walk braces
    while i < len(s):
        m = re.search(r'\bserver\s*\{', s[i:])
        if not m:
            out.append(s[i:]); break
        out.append(s[i:i+m.start()])
        # walk braces from m.end()
        start = i + m.start()
        j = i + m.end()
        depth = 1
        while j < len(s) and depth > 0:
            if s[j] == '{': depth += 1
            elif s[j] == '}': depth -= 1
            j += 1
        block = s[start:j]
        if 'admin.streamsuite.io' in block:
            pass  # drop
        else:
            out.append(block)
        i = j
    return ''.join(out)
new = strip_admin_blocks(src)
if new != src:
    with open(path, 'w') as f: f.write(new)
    print("stripped admin blocks from main streamsuite config")
else:
    print("no admin blocks in main config to strip")
PY

echo
echo "─── 4/5 ─── Add 404-for-admin-paths on main streamsuite.io ───"
# Inject `location /admin` and `/api/admin` 404 into the main streamsuite
# server block so admin paths on the public domain hard-404.
python3 - <<PY
import re
path = "$MAIN_CONF"
with open(path) as f: src = f.read()
INJECT = """
    # Admin paths only served from admin.streamsuite.io — 404 here.
    location /admin { return 404; }
    location /api/admin { return 404; }
"""
if 'Admin paths only served from admin.streamsuite.io' in src:
    print("admin 404 block already present")
else:
    # Insert right after the dotfiles block in the main server (port 443)
    m = re.search(r"(server_name\s+streamsuite\.io\s+www\.streamsuite\.io;[\s\S]*?location\s*~\s*/\\\.\s*\{[^}]*\}\s*)", src)
    if not m:
        # Fallback: insert before the catch-all location /
        m2 = re.search(r"(server_name\s+streamsuite\.io\s+www\.streamsuite\.io;[\s\S]*?)(\n\s*location\s*/\s*\{)", src)
        if m2:
            src = src[:m2.end(1)] + INJECT + src[m2.end(1):]
        else:
            print("ERROR: could not find injection point in main config")
            exit(1)
    else:
        src = src[:m.end(1)] + INJECT + src[m.end(1):]
    with open(path, 'w') as f: f.write(src)
    print("injected admin-404 block into main streamsuite config")
PY

echo
echo "─── 5/5 ─── Validate + reload nginx ───"
nginx -t
systemctl reload nginx
echo "✓ nginx reloaded"

echo
echo "─── DONE ───"
echo "Verify:"
echo "  curl -sI https://admin.streamsuite.io/admin/login         # should 200"
echo "  curl -sI https://admin.streamsuite.io/                     # should 404"
echo "  curl -sI https://admin.streamsuite.io/dashboard            # should 404"
echo "  curl -sI https://streamsuite.io/admin/login                # should 404"
echo "  curl -sI https://streamsuite.io/api/admin/auth/login       # should 404"
echo
echo "Then sign in at https://admin.streamsuite.io/admin/login"
echo "(Cookie set there cannot leak to streamsuite.io — host-scoped by default.)"
