#!/bin/bash
# streamsuite-sync.sh — pulls active customers from Hostinger and regenerates
# the nginx customer-key include file. Run as root via systemd timer every 5s.
#
# WHAT IT DOES
#   1. GET https://streamsuite.io/api/internal/customers with bearer auth
#   2. Generate nginx map fragments for keys + tiers
#   3. Atomic write to /etc/nginx/streamsuite_customers.inc.conf
#       and /etc/nginx/streamsuite_tiers.inc.conf
#   4. Reload nginx only if either file changed
#
# YOUR EXISTING NGINX MAPS must `include` these fragments. Suggested layout
# inside /etc/nginx/sites-available/streamsuite-bsc.conf:
#
#       map $arg_key $api_tier {
#           default "";
#           include /etc/nginx/rpc_api_keys.conf;          # your existing demo + manual
#           include /etc/nginx/streamsuite_customers.inc.conf;  # synced from Hostinger
#       }
#
# (and same pattern for tier mapping if you have one)
#
# SAFETY
#   - Does NOT touch your existing rpc_api_keys.conf (demo key + any manual adds).
#   - Idempotent — if no changes, no nginx reload.
#   - Fails closed: if Hostinger is unreachable or returns garbage, leaves
#     current file in place and emits a syslog warning.
#
# DEPS: curl, jq, nginx
# INSTALL: place at /usr/local/bin/streamsuite-sync.sh, chmod +x

set -euo pipefail

# ---- config ----
HOSTINGER_URL="${STREAMSUITE_SYNC_URL:-https://streamsuite.io/api/internal/customers}"
SYNC_SECRET_FILE="${STREAMSUITE_SYNC_SECRET_FILE:-/etc/streamsuite/sync-secret}"
KEYS_FILE="${STREAMSUITE_KEYS_FILE:-/etc/nginx/streamsuite_keys.inc.conf}"
TIERS_FILE="${STREAMSUITE_TIERS_FILE:-/etc/nginx/streamsuite_tiers.inc.conf}"
NGINX_CMD="${NGINX_CMD:-/usr/sbin/nginx}"
TAG="streamsuite-sync"

log() { logger -t "$TAG" -- "$*"; }

if [ ! -r "$SYNC_SECRET_FILE" ]; then
  log "missing or unreadable secret file: $SYNC_SECRET_FILE"
  exit 1
fi
SYNC_SECRET="$(< "$SYNC_SECRET_FILE")"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

RESPONSE="$TMP_DIR/response.json"
HTTP_CODE=$(curl -sS -o "$RESPONSE" -w "%{http_code}" \
  --max-time 10 \
  -H "Authorization: Bearer $SYNC_SECRET" \
  "$HOSTINGER_URL" || echo "000")

if [ "$HTTP_CODE" != "200" ]; then
  log "sync failed: HTTP $HTTP_CODE from $HOSTINGER_URL"
  exit 0  # don't break the timer; try again next tick
fi

if ! jq -e . "$RESPONSE" >/dev/null 2>&1; then
  log "sync failed: invalid JSON"
  exit 0
fi

# ---- generate nginx fragments ----
NEW_KEYS="$TMP_DIR/keys.conf"
NEW_TIERS="$TMP_DIR/tiers.conf"

# Keys map fragment: matches /etc/nginx/rpc_api_keys.conf format
#   "<api_key>" 1; # <email> - <tier>
{
  echo "# generated by streamsuite-sync at $(date -u +%FT%TZ)"
  echo "# format: \"<api_key>\" 1; # <email> - <tier>"
  jq -r '.customers[]? | "\"" + .api_key + "\" 1; # " + .email + " - " + .tier' "$RESPONSE"
} > "$NEW_KEYS"

# Tiers map fragment: matches /etc/nginx/rpc_tiers.conf format
#   "<api_key>" "<tier>";
{
  echo "# generated by streamsuite-sync at $(date -u +%FT%TZ)"
  echo "# format: \"<api_key>\" \"<tier>\";"
  jq -r '.customers[]? | "\"" + .api_key + "\" \"" + .tier + "\";"' "$RESPONSE"
} > "$NEW_TIERS"

# ---- atomic update if changed ----
CHANGED=0

update_if_changed() {
  local new_file="$1"
  local target="$2"
  # Compare data lines only — the "# generated at <timestamp>" header changes
  # every tick, so cmp -s would always report diff and trigger a needless
  # nginx reload (~13/min before this fix).
  if [ ! -f "$target" ] || ! diff -q <(grep -v '^#' "$new_file") <(grep -v '^#' "$target") >/dev/null 2>&1; then
    install -m 0644 "$new_file" "$target"
    CHANGED=1
    log "updated $target"
  fi
}

mkdir -p "$(dirname "$KEYS_FILE")"
update_if_changed "$NEW_KEYS" "$KEYS_FILE"
update_if_changed "$NEW_TIERS" "$TIERS_FILE"

# ---- reload nginx only if config actually changed ----
if [ "$CHANGED" = "1" ]; then
  if "$NGINX_CMD" -t 2>/dev/null; then
    "$NGINX_CMD" -s reload
    log "nginx reloaded"
  else
    log "nginx -t failed — NOT reloading (changes are in place but nginx config rejected them)"
  fi
fi

exit 0
